### ISSUE TITLE
MA35D03F764C 双网口，第二个网口无法识别的问题

### ISSUE THREAD

**Issue by Victccmc** [OpenNuvoton/Nuvoton-OpenWrt-22.03#10]
使用MA35D0编译出来的固件，无法识别到第二个网口：
![image](https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03/assets/139729366/be3e1eac-956c-4101-9d21-a72ac7f8a70f)
![image](https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03/assets/139729366/f6630720-a6db-48a9-a748-652f29dd8186)

之前怀疑是硬件问题，我们使用MA35D1编译的固件烧录到MA35D0的板子上，发现可以正常启动，且2个网口都可以正常工作：
<img width="497" alt="6fee9afa84297bd0c4824ec1fe97d16" src="https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03/assets/139729366/f012987f-f600-4463-b202-d9ada919f7ad">

请问一下，这个MA35D0的第二个网口是否有验证

**Comment by ccchang12** [comment]
@Victccmc , 這邊用最新版本BSP在MA35D0 IoT board上進行測試, eth1並沒有問題. 你可以比對下環境和log message有何不同之處. 
[d0iot_256m_nand_240626_01_eth1.log](https://github.com/user-attachments/files/15981677/d0iot_256m_nand_240626_01_eth1.log)

**Comment by Victccmc** [comment]
对比了启动LOG网口部分基本一致:
![image](https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03/assets/139729366/4cff73b8-651c-4814-a688-6d9a1e2dd78c)

我这边是使用的MA35D03F764C 对应是IOT_128M

**Comment by ccchang12** [comment]
@Victccmc 我們手上的MA35D0 IoT 128MB板子也是OK, 只有貴司的開發板會有問題. 因我們手上沒有貴司的開發板, 所以這個問題會由我司深圳的SAE來協助貴司解決.

**Comment by Victccmc** [comment]
好的  谢谢
