### ISSUE TITLE
Follow the steps of "NUVOTON OPENWRT 22.03 USER MANUAL " build MA35D1 fail

### ISSUE THREAD

**Issue by kylongmu** [OpenNuvoton/Nuvoton-OpenWrt-22.03#2]
Build NUC980 is OK, but build MA35D1 fail, this is the error message:

3867+1 records in
3868+0 records out
3960832 bytes (4.0 MB, 3.8 MiB) copied, 0.0124189 s, 319 MB/s
tar: Option --mtime: Treating date '@1662173734' as 2022-09-03 02:55:34
sysupgrade-512m-nand/
sysupgrade-512m-nand/CONTROL
sysupgrade-512m-nand/kernel
sysupgrade-512m-nand/root
echo '{  "metadata_version": "1.1", "compat_version": "1.0",   "supported_devices":["512m-nand"], "version": { "dist": "OpenWrt", "version": "22.03.0", "revision": "r19685-512e76967f", "target": "ma35d1/iot", "board": "512m-nand" } }' | fwtool -I - /home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin
sha256sum "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin" | cut -d" " -f1 > "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin.sha256sum"
[ ! -s "/home/ubuntu/Nuvoton-OpenWrt-22.03/key-build" -o ! -s "/home/ubuntu/Nuvoton-OpenWrt-22.03/key-build.ucert" -o ! -s "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin" ] || { cp "/home/ubuntu/Nuvoton-OpenWrt-22.03/key-build.ucert" "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin.ucert" ; usign -S -m "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin" -s "/home/ubuntu/Nuvoton-OpenWrt-22.03/key-build" -x "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin.sig" ; ucert -A -c "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin.ucert" -x "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin.sig" ; fwtool -S "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin.ucert" "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin" ; }
cp /home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin /home/ubuntu/Nuvoton-OpenWrt-22.03/bin/targets/ma35d1/iot/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin
DEVICE_ID="512m-nand" SOURCE_DATE_EPOCH=1662173734 FILE_NAME="openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin" FILE_DIR="/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp" FILE_TYPE=sysupgrade FILE_FILESYSTEM="squashfs" DEVICE_IMG_PREFIX="openwrt-ma35d1-iot-512m-nand" DEVICE_VENDOR="" DEVICE_MODEL="IoT" DEVICE_VARIANT="512M with NAND" DEVICE_ALT0_VENDOR="" DEVICE_ALT0_MODEL="" DEVICE_ALT0_VARIANT="" DEVICE_ALT1_VENDOR="" DEVICE_ALT1_MODEL="" DEVICE_ALT1_VARIANT="" DEVICE_ALT2_VENDOR="" DEVICE_ALT2_MODEL="" DEVICE_ALT2_VARIANT="" DEVICE_TITLE=" IoT 512M with NAND" DEVICE_PACKAGES="" TARGET="ma35d1" SUBTARGET="iot" VERSION_NUMBER="22.03.0" VERSION_CODE="r19685-512e76967f" SUPPORTED_DEVICES="512m-nand" /home/ubuntu/Nuvoton-OpenWrt-22.03/scripts/json_add_image_info.py /home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/json_info_files/openwrt-ma35d1-iot-512m-nand-squashfs-sysupgrade.bin.json
[ -f /home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/512m-nand-uImage -a -f /home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/root.squashfs ]
sed -i 1,/\^$/d /tmp/openwrt.env
**sed: can't read /tmp/openwrt.env: No such file or directory**
make[5]: *** [Makefile:112: /home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/linux-ma35d1_iot/tmp/openwrt-ma35d1-iot-512m-nand-squashfs-image-dtb] Error 2
make[5]: Leaving directory '/home/ubuntu/Nuvoton-OpenWrt-22.03/target/linux/ma35d1/image'
make[4]: *** [Makefile:25: install] Error 2
make[4]: Leaving directory '/home/ubuntu/Nuvoton-OpenWrt-22.03/target/linux/ma35d1'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/home/ubuntu/Nuvoton-OpenWrt-22.03/target/linux'
time: target/linux/install#21.35#16.27#41.51
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/install] Error 1
make[2]: Leaving directory '/home/ubuntu/Nuvoton-OpenWrt-22.03'
make[1]: *** [target/Makefile:24: /home/ubuntu/Nuvoton-OpenWrt-22.03/staging_dir/target-aarch64_cortex-a35_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/ubuntu/Nuvoton-OpenWrt-22.03'
make: *** [/home/ubuntu/Nuvoton-OpenWrt-22.03/include/toplevel.mk:230: world] Error 2

**Comment by ccchang12** [comment]
@kylongmu Please run the command "touch /tmp/openwrt.env" just one time to avoid this issue, I will modify the SDK to fix it.

**Comment by kylongmu** [comment]
![openwrt22](https://user-images.githubusercontent.com/28899073/216531858-b8843c2b-0a08-4319-b0e9-7dfdc3490e83.png)
this is the MA35D1 compiled output, is't correct?

**Comment by ccchang12** [comment]
@kylongmu Yes. The most important output file is the XXX-pack.bin, you can check it.
