### ISSUE TITLE
[No module named 'Cryptodome']Build with most recent pull, get some errors

### ISSUE THREAD

**Issue by kylongmu** [OpenNuvoton/Nuvoton-OpenWrt-22.03#3]
make[4]: Entering directory '/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/optee-ma35d1-generic/optee-ma35d1-2022-11-28-49e947a8'
  CHK     out/arm-plat-nuvoton/conf.mk
  CHK     out/arm-plat-nuvoton/include/generated/conf.h
  GEN     out/arm-plat-nuvoton/core/ta_pub_key.c
Traceback (most recent call last):
  File "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/optee-ma35d1-generic/optee-ma35d1-2022-11-28-49e947a8/scripts/pem_to_pub_c.py", line 61, in <module>
    main()
  File "/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/optee-ma35d1-generic/optee-ma35d1-2022-11-28-49e947a8/scripts/pem_to_pub_c.py", line 24, in main
    from Cryptodome.PublicKey import RSA
ModuleNotFoundError: No module named 'Cryptodome'
make[4]: *** [mk/subdir.mk:162: out/arm-plat-nuvoton/core/ta_pub_key.c] Error 1
make[4]: Leaving directory '/home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/optee-ma35d1-generic/optee-ma35d1-2022-11-28-49e947a8'
make[3]: *** [Makefile:57: /home/ubuntu/Nuvoton-OpenWrt-22.03/build_dir/target-aarch64_cortex-a35_musl/optee-ma35d1-generic/optee-ma35d1-2022-11-28-49e947a8/.built] Error 2
make[3]: Leaving directory '/home/ubuntu/Nuvoton-OpenWrt-22.03/package/boot/optee-ma35d1'
time: package/boot/optee-ma35d1/generic/compile#2.84#0.71#3.31
    ERROR: package/boot/optee-ma35d1 failed to build (build variant: generic).
make[2]: *** [package/Makefile:116: package/boot/optee-ma35d1/compile] Error 1
make[2]: Leaving directory '/home/ubuntu/Nuvoton-OpenWrt-22.03'
make[1]: *** [package/Makefile:110: /home/ubuntu/Nuvoton-OpenWrt-22.03/staging_dir/target-aarch64_cortex-a35_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ubuntu/Nuvoton-OpenWrt-22.03'
make: *** [/home/ubuntu/Nuvoton-OpenWrt-22.03/include/toplevel.mk:230：world] Error 2

**Comment by kylongmu** [comment]
nuc980 build is Ok, ma35d1 fail.

**Comment by ccchang12** [comment]
This should be a build environment issue. You need to install the Cryptodome library. You can do so through _sudo apt install python3-pycryptodome_, _pip install pycryptodome_ or __pip3 install pycryptodomex_.

If you cannot fix it, we suggest you can use the docker environment to build OpenWrt images.

**Comment by kylongmu** [comment]
> This should be a build environment issue. You need to install the Cryptodome library. You can do so through _sudo apt install python3-pycryptodome_, _pip install pycryptodome_ or __pip3 install pycryptodomex_.
> 
> If you cannot fix it, we suggest you can use the docker environment to build OpenWrt images.

Thanks, with "sudo apt install python3-pycryptodome" , the build is ok.
I also use the docker environment, but it faild with another problem, I issued https://github.com/OpenNuvoton/MA35D1_Docker_Script/issues/1#issue-1520362292
