### ISSUE TITLE
能支持970吗？

### ISSUE THREAD

**Issue by bing20138163** [OpenNuvoton/Nuvoton-OpenWrt-22.03#4]
openwrt 想移植在970版本，后续可以支持在970系列吗

**Comment by ychuang3** [comment]
我們目前並沒有這個計畫，短期內也沒有。
建議使用 NUC980

**Comment by thinpv** [comment]
but NUC980 doesn't have LCD controller, and Openwrt is easier to use than Buildroot. It would be better if NUC970 could use Openwrt

**Comment by ychuang3** [comment]
OpenWrt does not support kernel version lower than 3.18.

**Comment by MarsHo1970** [comment]
> 

https://github.com/OpenNuvoton/NUC970-linux-5.10.y

**Comment by MarsHo1970** [comment]
> 

NUC970还是有很多人在用的

**Comment by ychuang3** [comment]
是的，我們正在進行 porting linux-5.10 到 NUC970 platform
快的話下個月 release
有了 linux-5.10, 才有可能支持 OpenWrt-22.03
然而 NUC970 是否 support OpenWrt-22.03, 目前還在討論中

**Comment by ccchang12** [comment]
NUC970/N9H30 platform already supports OpenWrt-22.03 now.

**Comment by bing20138163** [comment]
我用的是config_nuc970_evb配置，烧录我977DK61Y和972DF62Y都无法正常启动？看内核配置只支持972？ Nuvoton NUC970/N9H30 Series Development Board (Nuvoton NUC972 evaluation board using device ？但是我972的开发板也不行，不知道是否其他原因造成。。。（972提示NUC970 IBR 20151008.1735
No Key
Bootttttt搟k?s#S）

**Comment by bing20138163** [comment]
![972](https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03/assets/70122913/12ad3dcd-b86b-4c3a-8524-350cbb145f86)

**Comment by bing20138163** [comment]
![Uploading 9722.jpg…]()

**Comment by bing20138163** [comment]
![9722](https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03/assets/70122913/f0086b6f-2ecc-4c28-9316-ed00baef5f9b)

**Comment by ccchang12** [comment]
@bing20138163 我這邊測試的EVB板是 NHS-972-1-CY-1M55, 請問你測試的是哪一片板子?

**Comment by bing20138163** [comment]
> NHS-972-1-CY-1M55

我现在不是用这个板子，不过都是nandflash启动的应该没咋影响吧？

**Comment by ccchang12** [comment]
@bing20138163 你目前的狀況應該是卡在一開始的Uboot, 還沒進到Linux kernel. 我這邊需要知道詳細訊息來複製issue, 才能夠進行下一步動作. 請問你測試的是哪一片板子?

**Comment by bing20138163** [comment]
> @bing20138163 你目前的狀況應該是卡在一開始的Uboot, 還沒進到Linux kernel. 我這邊需要知道詳細訊息來複製issue, 才能夠進行下一步動作. 請問你測試的是哪一片板子?

现在手在不是官方的板子，之前官方板子早就还给代理了，现在用的比较早在淘宝上面买的，主芯片是972DF62Y
![972](https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03/assets/70122913/e8c02390-2d8b-4a5e-b8d9-e6ce3a9821b0)

**Comment by bing20138163** [comment]
@ccchang12 手在977板子也都是非官方的

**Comment by ccchang12** [comment]
@bing20138163 麻煩你留下聯絡訊息, 我們這邊會請FAE team來處理.

**Comment by bing20138163** [comment]
@ccchang12 通过还原uboot AES decrypt image with MTP NAND-boot key ,现在972可以正常启动到内核了，什么时候适配977？
![luci](https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03/assets/70122913/32e07936-3981-4eb6-b175-936812b3dc33)

**Comment by bing20138163** [comment]
@ccchang12 目前应该只适配972还没适配977内核吧，我烧录到977启动到内核会一直重启，具体log信息如下：
[977error.txt](https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03/files/13521500/977error.txt)

**Comment by ychuang3** [comment]
請檢查你的 kernel image size

從 log 看
NAND read: device 0 offset 0x200000, size 0x600000
 6291456 bytes read: OK

只有從 NAND 讀取 6MB 到 DRAM
如果你的 kernel image 大於 6MB，就沒有完整 load 到 DRAM，
會有這種狀況，應該 watchdog reset

如果你的 kernel image 大於 6MB，需要修改 u-boot script 載入更多

**Comment by bing20138163** [comment]
> @ccchang12 目前应该只适配972还没适配977内核吧，我烧录到977启动到内核会一直重启，具体log信息如下： [977error.txt](https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03/files/13521500/977error.txt)

已解决，修改一下dts nand配置就可以
