### ISSUE TITLE
发现nuc972的无法使用硬件spi1?

### ISSUE THREAD

**Issue by bing20138163** [OpenNuvoton/Nuvoton-OpenWrt-22.03#6]
同样的设备驱动，spi0可以，spi1不行（dts会报无法配置spi1控制器）

**Comment by ccchang12** [comment]
@bing20138163 由於你不是用我們公板, 我們這邊無法進行問題複製. 麻煩留下聯絡訊息, 我們會請FAE team來後續處理.

**Comment by didadidadi5** [comment]
使用青联奇创的nuc977跑openwrt，backport5.15.58编译的r8188eu驱动能OK？
