### ISSUE TITLE
backport5.15.58-1编译mt7601，驱动加载fail！

### ISSUE THREAD

**Issue by didadidadi5** [OpenNuvoton/Nuvoton-OpenWrt-22.03#7]
发送厂商请求没有应答！

**Comment by ccchang12** [comment]
@didadidadi5 我用最新版本之 BSP 來測試 mt7601u, kernel module 的 building 和 loading, 都是 OK 的. 請提供您的 error message.

[building]
cczhang@cczhang-VirtualBox:~/opennuvoton/Nuvoton-OpenWrt-22.03_wifi_a35/build_dir/target-aarch64_generic_musl/linux-ma35d1_iot/backports-5.15.58-1(master)$ find . | grep mt7601u.ko$
./drivers/net/wireless/mediatek/mt7601u/mt7601u.ko
./ipkg-aarch64_generic/kmod-mt7601u/lib/modules/5.10.140/mt7601u.ko
./.pkgdir/kmod-mt7601u/lib/modules/5.10.140/mt7601u.ko

[loading]
root@OpenWrt:/# lsmod | grep mt7601
cfg80211              327680  2 mt7601u,mac80211
compat                 20480  3 mt7601u,mac80211,cfg80211,[permanent]
mac80211              606208  1 mt7601u
mt7601u                69632  0

**Comment by didadidadi5** [comment]
你应该没有插入实际的网卡吧，我用5.10.140的内核，openwrt22.03的mac80211这个包编译出来的mt7601u.ko安装和lsmod都没有问题，就是插入实际网卡就报下面的错误，我的是nuc977的板子。root@OpenWrt:/# lsmod |grep mt7601u
cfg80211              294912  2 mt7601u,mac80211
compat                 16384  3 mt7601u,mac80211,cfg80211,[permanent]
mac80211              565248  1 mt7601u
mt7601u                61440  0 
root@OpenWrt:/# 
 mt7601u 1-2:1.0: ASIC revision: 76010001 MAC revision: 76010500
[   27.695233] mt7601u 1-2:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[   28.201774] mt7601u 1-2:1.0: EEPROM ver:0d fae:00
[   28.365258] usb 1-2: USB disconnect, device number 2
[   28.370424] mt7601u 1-2:1.0: Error: submit URB dir:128 ep:1 failed:-19
[   28.380691] mt7601u 1-2:1.0: Error: submit RX URB failed:-19
[   28.443683] usbcore: registered new interface driver mt7601u
[   28.728116] PPP generic driver version 2.4.2
[   28.751416] NET: Registered protocol family 24
[   28.803433] usb 1-2: new high-speed USB device number 3 using nuc970-ehci
[   28.817499] kmodloader: done loading kernel modules from /etc/modules.d/*
[   28.973266] usb 1-2: device descriptor read/64, error -71
[   29.553324] usb 1-2: reset high-speed USB device number 3 using nuc970-ehci
[   29.778883] mt7601u 1-2:1.0: ASIC revision: 76010001 MAC revision: 76010500
[   29.798958] mt7601u 1-2:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[   30.372508] mt7601u 1-2:1.0: EEPROM ver:0d fae:00
[   30.555308] mt7601u 1-2:1.0: Error: MCU resp evt:0 seq:2-1!
[   30.561224] mt7601u 1-2:1.0: Error: MCU resp evt:0 seq:2-1!
[   30.581299] mt7601u 1-2:1.0: Error: MCU resp evt:0 seq:2-1!
[   30.593266] mt7601u 1-2:1.0: Error: MCU resp evt:0 seq:2-1!
[   30.599208] mt7601u 1-2:1.0: Error: MCU resp evt:0 seq:2-1!
[   30.613333] mt7601u 1-2:1.0: Error: mt7601u_mcu_wait_resp timed out
[   34.753324] mt7601u 1-2:1.0: Vendor request req:07 off:0080 failed:-110
[   39.006999] mt7601u 1-2:1.0: Vendor request req:02 off:0080 failed:-110
[   42.753341] mt7601u 1-2:1.0: Vendor request req:02 off:0080 failed:-110
[   42.760174] mt7601u: probe of 1-2:1.0 failed with error -110
[   42.824683] usb 1-2: USB disconnect, device number 3
[   43.345858] usb 1-2: new high-speed USB device number 4 using nuc970-ehci
[   48.593266] usb 1-2: device descriptor read/64, error -110
[   64.033341] usb 1-2: device descriptor read/64, error -110
[   64.731233] usb 1-2: new high-speed USB device number 5 using nuc970-ehci
[   69.953333] usb 1-2: device descriptor read/64, error -110

**Comment by ychuang3** [comment]
注意到其中訊息:  
```
 [ 28.973266] usb 1-2: device descriptor read/64, error -71   
```
get device descriptor 是枚舉的第一個 command，就失敗了，這比較奇怪。

```
[ 29.553324] usb 1-2: reset high-speed USB device number 3 using nuc970-ehci
```
在 linux 嘗試 reset device 之後，看起來枚舉成功了，
```
[ 29.778883] mt7601u 1-2:1.0: ASIC revision: 76010001 MAC revision: 76010500
[ 29.798958] mt7601u 1-2:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[ 30.372508] mt7601u 1-2:1.0: EEPROM ver:0d fae:00
```
這三條訊息似乎是 device 回應的 string descriptor，  (可以連接到 Windows PC 讀取 device 訊息確認)
2013 年有點久遠

後面發送 vendor command 不被網卡接受，
```
 [ 30.555308] mt7601u 1-2:1.0: Error: MCU resp evt:0 seq:2-1!
```
因此懷疑使用的 mt7601u driver 與 網卡 firmware 不匹配

這跟 OpenWrt BSP 無關，請取得版本匹配的 driver

**Comment by didadidadi5** [comment]
用x86的Ubuntu22.04自带的mt7601u实际上也是抱这个错误！新内核并没有兼容这种旧驱动？

**Comment by ychuang3** [comment]
內核自帶的 driver 應該是可靠的，問題可能出在網卡 firmware，
您可以將問題發到 MediaTek 相關論壇

**Comment by ychuang3** [comment]
忽略了一點, 因為這是 linux 5.15 的 driver, porting 到 5.10 無法運作，也是可能的。
所以不見得是網卡 firmware 問題，比較大可能是版本匹配
建議尋找 版本更相近的 driver 嘗試

**Comment by ccchang12** [comment]
在Kernel 5.10裡面, 使用5.15的WiFi driver, 是OpenWrt 22.03的預設環境, 之前我們跑rtl8192cu和rtl8723bs都OK. 這次找了一片mt7601u, 跑在NUC980和MA35D1, 也都是OK, log message如下. 我們手上的mt7601u firmware版本跟您一樣, 應該也不是root cause. 因為NUC977並非我們support的OpenWrt platform, 建議您能夠檢查一下您的相關環境或設定.

**root@OpenWrt:/# [  105.752191] usb 1-2: new high-speed USB device number 2 using nuc980-ehci
[  106.502241] usb 1-2: reset high-speed USB device number 2 using nuc980-ehci
[  106.705674] mt7601u 1-2:1.0: ASIC revision: 76010001 MAC revision: 76010500
[  106.719141] mt7601u 1-2:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[  107.218183] mt7601u 1-2:1.0: EEPROM ver:0a fae:00**

root@OpenWrt:/# 
root@OpenWrt:/# ifconfig -a
dummy0    Link encap:Ethernet  HWaddr 26:11:A4:84:65:CC  
          BROADCAST NOARP  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 08:00:27:00:01:92  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:32 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:72 errors:0 dropped:0 overruns:0 frame:0
          TX packets:72 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:5616 (5.4 KiB)  TX bytes:5616 (5.4 KiB)

**wlan0     Link encap:Ethernet  HWaddr 00:0C:43:36:80:BC  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)**

**Comment by didadidadi5** [comment]
> 在Kernel 5.10裡面, 使用5.15的WiFi driver, 是OpenWrt 22.03的預設環境, 之前我們跑rtl8192cu和rtl8723bs都OK. 這次找了一片mt7601u, 跑在NUC980和MA35D1, 也都是OK, log message如下. 我們手上的mt7601u firmware版本跟您一樣, 應該也不是root cause. 因為NUC977並非我們support的OpenWrt platform, 建議您能夠檢查一下您的相關環境或設定.
> 
> **root@OpenWrt:/# [  105.752191] usb 1-2: new high-speed USB device number 2 using nuc980-ehci
> [  106.502241] usb 1-2: reset high-speed USB device number 2 using nuc980-ehci
> [  106.705674] mt7601u 1-2:1.0: ASIC revision: 76010001 MAC revision: 76010500
> [  106.719141] mt7601u 1-2:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
> [  107.218183] mt7601u 1-2:1.0: EEPROM ver:0a fae:00**
> 
> root@OpenWrt:/# 
> root@OpenWrt:/# ifconfig -a
> dummy0    Link encap:Ethernet  HWaddr 26:11:A4:84:65:CC  
>           BROADCAST NOARP  MTU:1500  Metric:1
>           RX packets:0 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
> 
> eth0      Link encap:Ethernet  HWaddr 08:00:27:00:01:92  
>           UP BROADCAST MULTICAST  MTU:1500  Metric:1
>           RX packets:0 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:32 
>           RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
> 
> lo        Link encap:Local Loopback  
>           inet addr:127.0.0.1  Mask:255.0.0.0
>           inet6 addr: ::1/128 Scope:Host
>           UP LOOPBACK RUNNING  MTU:65536  Metric:1
>           RX packets:72 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:72 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:5616 (5.4 KiB)  TX bytes:5616 (5.4 KiB)
> 
> **wlan0     Link encap:Ethernet  HWaddr 00:0C:43:36:80:BC  
>           BROADCAST MULTICAST  MTU:1500  Metric:1
>           RX packets:0 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)**
> 
> 
> 
> 

> - EEPROM版本不同会造成驱动加载失败？
