### ISSUE TITLE
backport5.15.58-1编译r8188eu驱动ok时nl80211不支持，不ok时各种结构体成员未定义？

### ISSUE THREAD

**Issue by didadidadi5** [OpenNuvoton/Nuvoton-OpenWrt-22.03#8]
ERROR: modpost: "wireless_send_event" [/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/net/wireless/lib80211_crypt_tkip.ko] undefined!
ERROR: module '/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/drivers/staging/r8188eu/r8188eu.ko' is missing.

**Comment by ychuang3** [comment]
error message 已經指出 "wireless_send_event" undefined
這是位於 net/wireless/wext-core.c 裡面
需要打開 menuconfig  CONFIG_WEXT_CORE

**Comment by didadidadi5** [comment]
make[2]: Entering directory '/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/package/kernel/mac80211'
rm -f /media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/.built
touch /media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/.built_check
. /media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/include/shell.sh; var2file "V_mac80211_config" /media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/.config
make -C "/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1" KCFLAGS="-fmacro-prefix-map=/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi=target-arm_arm926ej-s_musl_eabi -fno-caller-saves " HOSTCFLAGS="-O2 -I/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/staging_dir/host/include -I/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/staging_dir/hostpkg/include -I/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/staging_dir/target-arm_arm926ej-s_musl_eabi/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sat Sep  3 02:55:34 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/symvers/mac80211.symvers" EXTRA_CFLAGS="-I/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/include -fmacro-prefix-map=/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1=backports-5.15.58-1 " KLIB_BUILD="/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/linux-git_github_com_didadidadi5_NUC970_linux_5_10_y_git-HEAD" MODPROBE=true KLIB=/lib/modules/5.10.140 KERNEL_SUBLEVEL=10 KBUILD_LDFLAGS_MODULE_PREREQ= allnoconfig
make[3]: Entering directory '/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1'
make[4]: 'Kconfig.versions' is up to date.
make[5]: 'conf' is up to date.
boolean symbol CRYPTO_LIB_ARC4 tested for 'm'? test forced to 'n'

WARNING: unmet direct dependencies detected for CFG80211_WEXT
  Depends on [n]: CFG80211 [=m] && WEXT_CORE
  Selected by [m]:
  - RTL8723BS [=m] && STAGING [=y] && !KERNEL_5_4 && WLAN [=y] && MMC [=y] && CFG80211 [=m] && m && BP_MODULES [=y]

WARNING: unmet direct dependencies detected for CFG80211_WEXT
  Depends on [n]: CFG80211 [=m] && WEXT_CORE
  Selected by [m]:
  - RTL8723BS [=m] && STAGING [=y] && !KERNEL_5_4 && WLAN [=y] && MMC [=y] && CFG80211 [=m] && m && BP_MODULES [=y]
#
# configuration written to .config
#
make[3]: Leaving directory '/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1'
rm -rf /media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/modules
make  -C "/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1" KCFLAGS="-fmacro-prefix-map=/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi=target-arm_arm926ej-s_musl_eabi -fno-caller-saves " HOSTCFLAGS="-O2 -I/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/staging_dir/host/include -I/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/staging_dir/hostpkg/include -I/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/staging_dir/target-arm_arm926ej-s_musl_eabi/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sat Sep  3 02:55:34 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/symvers/mac80211.symvers" EXTRA_CFLAGS="-I/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/include -fmacro-prefix-map=/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1=backports-5.15.58-1 " KLIB_BUILD="/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/linux-git_github_com_didadidadi5_NUC970_linux_5_10_y_git-HEAD" MODPROBE=true KLIB=/lib/modules/5.10.140 KERNEL_SUBLEVEL=10 KBUILD_LDFLAGS_MODULE_PREREQ= modules
make[3]: Entering directory '/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1'
make[4]: 'Kconfig.versions' is up to date.
make[6]: 'Kconfig.versions' is up to date.
make[7]: 'conf' is up to date.
boolean symbol CRYPTO_LIB_ARC4 tested for 'm'? test forced to 'n'

WARNING: unmet direct dependencies detected for CFG80211_WEXT
  Depends on [n]: CFG80211 [=m] && WEXT_CORE
  Selected by [m]:
  - RTL8723BS [=m] && STAGING [=y] && !KERNEL_5_4 && WLAN [=y] && MMC [=y] && CFG80211 [=m] && m && BP_MODULES [=y]

WARNING: unmet direct dependencies detected for CFG80211_WEXT
  Depends on [n]: CFG80211 [=m] && WEXT_CORE
  Selected by [m]:
  - RTL8723BS [=m] && STAGING [=y] && !KERNEL_5_4 && WLAN [=y] && MMC [=y] && CFG80211 [=m] && m && BP_MODULES [=y]
#
# configuration written to .config
#
Building backport-include/backport/autoconf.h ... done.
  MODPOST /media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/Module.symvers
ERROR: modpost: "iwe_stream_add_point" [/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/net/wireless/cfg80211.ko] undefined!
ERROR: modpost: "wireless_send_event" [/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/net/wireless/cfg80211.ko] undefined!
ERROR: modpost: "iwe_stream_add_event" [/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/net/wireless/cfg80211.ko] undefined!
ERROR: modpost: "iwe_stream_add_value" [/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/net/wireless/cfg80211.ko] undefined!
make[7]: *** [scripts/Makefile.modpost:124: /media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/Module.symvers] Error 1
make[7]: *** Deleting file '/media/abc/c2581c9b-5fe0-48b3-b3f0-c21f631b0e37/abc/Nuvoton-OpenWrt-22.03/build_dir/target-arm_arm926ej-s_musl_eabi/linux-nuc970_evb/backports-5.15.58-1/Module.symvers'
make[6]: *** [Makefile:1737: modules] Error 2
make[5]: *** [Makefile.build:13: modules] Error 2
make[4]: *** [Makefile.real:93: modules] Error 2
make[3]: *** [Makefile:121: modules] Error 2



.config.target,.config.set,/generic/.config-5.10 have
CONFIG_WEXT_CORE=y
CONFIG_WEXT_PRIV=y
CONFIG_WEXT_PROC=y
CONFIG_WEXT_SPY=y

**Comment by ccchang12** [comment]
Hi @didadidadi5 , 之前在測試中發現, 部分WiFi source, 在backports中的5.15 source沒辦法被編譯到. 像下列的wext-core.c, 只有下面的Linux 5.10部分會被編譯到.
$BUILD_DIR/$LINUX_DIR/backports-5.15.58-1/net/wireless/wext-core.c
$BUILD_DIR/$LINUX_DIR/linux-github_com_OpenNuvoton_MA35D1_linux_5_10_y_git-053068f87dfae465ecbeeb006089279bdccad154/net/wireless/wext-core.c

針對這個issue, 解決方式是缺少的部分要從Linux 5.10來選. 請在make linux-menuconfig下, 打開下列wireless extension相關選項.
-*- Networking support  --->  [*]   Wireless  --->  [*]   Wireless extensions
-*- Networking support  --->  [*]   Wireless  --->  [*]   WEXT_SPY
-*- Networking support  --->  [*]   Wireless  --->  [*]   WEXT_PRIV

關於這部分的update, 請參考 https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03/commit/3690050b35a5ba056b3aa39a762709b7c51675ec, 我看其他platform例如 i.MX, 也是這樣解決的.
