### ISSUE TITLE
ubuntu 22.04  uname -r 5.15.0-78-generic 自带的mt7601u驱动log

### ISSUE THREAD

**Issue by didadidadi5** [OpenNuvoton/Nuvoton-OpenWrt-22.03#9]
[ 1172.731475] usb 1-1.1.3: new high-speed USB device number 6 using ehci-pci
[ 1172.863590] usb 1-1.1.3: New USB device found, idVendor=148f, idProduct=7601, bcdDevice= 0.00
[ 1172.863599] usb 1-1.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1172.863602] usb 1-1.1.3: Product: 802.11 n WLAN
[ 1172.863603] usb 1-1.1.3: Manufacturer: MediaTek
[ 1172.863605] usb 1-1.1.3: SerialNumber: 1.0
[ 1172.983199] usb 1-1.1.3: reset high-speed USB device number 6 using ehci-pci
[ 1173.110797] mt7601u 1-1.1.3:1.0: ASIC revision: 76010001 MAC revision: 76010500
[ 1173.117769] mt7601u 1-1.1.3:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[ 1173.508507] mt7601u 1-1.1.3:1.0: EEPROM ver:0d fae:00
[ 1173.689271] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1173.689284] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1173.693844] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1173.693851] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1173.698334] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1173.698341] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1173.702604] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1173.702612] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1173.706771] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1173.706779] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1173.706784] mt7601u 1-1.1.3:1.0: Error: mt7601u_mcu_wait_resp timed out
[ 1173.774837] usb 1-1.1.3: USB disconnect, device number 6
[ 1173.794632] mt7601u: probe of 1-1.1.3:1.0 failed with error -110
[ 1173.794716] usbcore: registered new interface driver mt7601u
[ 1174.038434] usb 1-1.1.3: new high-speed USB device number 7 using ehci-pci
[ 1174.170359] usb 1-1.1.3: New USB device found, idVendor=148f, idProduct=7601, bcdDevice= 0.00
[ 1174.170375] usb 1-1.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1174.170383] usb 1-1.1.3: Product: 802.11 n WLAN
[ 1174.170388] usb 1-1.1.3: Manufacturer: MediaTek
[ 1174.170394] usb 1-1.1.3: SerialNumber: 1.0
[ 1174.270196] usb 1-1.1.3: reset high-speed USB device number 7 using ehci-pci
[ 1174.397647] mt7601u 1-1.1.3:1.0: ASIC revision: 76010001 MAC revision: 76010500
[ 1174.399414] mt7601u 1-1.1.3:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[ 1174.792892] mt7601u 1-1.1.3:1.0: EEPROM ver:0d fae:00
[ 1174.970770] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1174.970782] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1174.975333] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1174.975342] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1174.979514] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1174.979521] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1174.983642] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1174.983650] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1174.987921] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1174.987934] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1174.987939] mt7601u 1-1.1.3:1.0: Error: mt7601u_mcu_wait_resp timed out
[ 1175.205571] mt7601u 1-1.1.3:1.0: Vendor request req:07 off:0080 failed:-71
[ 1175.425357] mt7601u 1-1.1.3:1.0: Vendor request req:02 off:0080 failed:-71
[ 1175.629235] mt7601u 1-1.1.3:1.0: Vendor request req:02 off:0080 failed:-71
[ 1175.629288] mt7601u: probe of 1-1.1.3:1.0 failed with error -110
[ 1175.633932] usb 1-1.1.3: USB disconnect, device number 7
[ 1175.880965] usb 1-1.1.3: new high-speed USB device number 8 using ehci-pci
[ 1176.020777] usb 1-1.1.3: New USB device found, idVendor=148f, idProduct=7601, bcdDevice= 0.00
[ 1176.020790] usb 1-1.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1176.020795] usb 1-1.1.3: Product: 802.11 n WLAN
[ 1176.020798] usb 1-1.1.3: Manufacturer: MediaTek
[ 1176.020801] usb 1-1.1.3: SerialNumber: 1.0
[ 1176.128782] usb 1-1.1.3: reset high-speed USB device number 8 using ehci-pci
[ 1176.252019] mt7601u 1-1.1.3:1.0: ASIC revision: 76010001 MAC revision: 76010500
[ 1176.253455] mt7601u 1-1.1.3:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[ 1176.649511] mt7601u 1-1.1.3:1.0: EEPROM ver:0d fae:00
[ 1176.820150] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1176.820163] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1176.824662] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1176.824673] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1176.828891] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1176.828901] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1176.833143] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1176.833152] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1176.837397] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1176.837406] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1176.837409] mt7601u 1-1.1.3:1.0: Error: mt7601u_mcu_wait_resp timed out
[ 1177.048088] mt7601u 1-1.1.3:1.0: Vendor request req:07 off:0080 failed:-71
[ 1177.260041] mt7601u 1-1.1.3:1.0: Vendor request req:02 off:0080 failed:-71
[ 1177.459790] mt7601u 1-1.1.3:1.0: Vendor request req:02 off:0080 failed:-71
[ 1177.459850] mt7601u: probe of 1-1.1.3:1.0 failed with error -110
[ 1177.464519] usb 1-1.1.3: USB disconnect, device number 8
[ 1177.703647] usb 1-1.1.3: new high-speed USB device number 9 using ehci-pci
[ 1177.839595] usb 1-1.1.3: New USB device found, idVendor=148f, idProduct=7601, bcdDevice= 0.00
[ 1177.839609] usb 1-1.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1177.839615] usb 1-1.1.3: Product: 802.11 n WLAN
[ 1177.839618] usb 1-1.1.3: Manufacturer: MediaTek
[ 1177.839621] usb 1-1.1.3: SerialNumber: 1.0
[ 1177.943429] usb 1-1.1.3: reset high-speed USB device number 9 using ehci-pci
[ 1178.071327] mt7601u 1-1.1.3:1.0: ASIC revision: 76010001 MAC revision: 76010500
[ 1178.073371] mt7601u 1-1.1.3:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[ 1178.485693] mt7601u 1-1.1.3:1.0: EEPROM ver:0d fae:00
[ 1178.672707] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1178.672719] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1178.677141] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1178.677149] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1178.681432] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1178.681442] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1178.685637] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1178.685646] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1178.692771] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1178.692784] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1178.692788] mt7601u 1-1.1.3:1.0: Error: mt7601u_mcu_wait_resp timed out
[ 1178.898711] mt7601u 1-1.1.3:1.0: Vendor request req:07 off:0080 failed:-71
[ 1179.098676] mt7601u 1-1.1.3:1.0: Vendor request req:02 off:0080 failed:-71
[ 1179.298522] mt7601u 1-1.1.3:1.0: Vendor request req:02 off:0080 failed:-71
[ 1179.298577] mt7601u: probe of 1-1.1.3:1.0 failed with error -110
[ 1179.312844] usb 1-1.1.3: USB disconnect, device number 9
[ 1179.546386] usb 1-1.1.3: new high-speed USB device number 10 using ehci-pci
[ 1179.678312] usb 1-1.1.3: New USB device found, idVendor=148f, idProduct=7601, bcdDevice= 0.00
[ 1179.678321] usb 1-1.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1179.678324] usb 1-1.1.3: Product: 802.11 n WLAN
[ 1179.678326] usb 1-1.1.3: Manufacturer: MediaTek
[ 1179.678328] usb 1-1.1.3: SerialNumber: 1.0
[ 1179.782161] usb 1-1.1.3: reset high-speed USB device number 10 using ehci-pci
[ 1179.905649] mt7601u 1-1.1.3:1.0: ASIC revision: 76010001 MAC revision: 76010500
[ 1179.907467] mt7601u 1-1.1.3:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[ 1180.336409] mt7601u 1-1.1.3:1.0: EEPROM ver:0d fae:00
[ 1180.510659] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1180.510673] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1180.514772] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1180.514785] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1180.519035] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1180.519047] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1180.523287] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1180.523296] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1180.527555] mt7601u 1-1.1.3:1.0: Error: MCU resp urb failed:-71
[ 1180.527565] mt7601u 1-1.1.3:1.0: Error: MCU resp evt:0 seq:4-3!
[ 1180.527570] mt7601u 1-1.1.3:1.0: Error: mt7601u_mcu_wait_resp timed out
[ 1180.733411] mt7601u 1-1.1.3:1.0: Vendor request req:07 off:0080 failed:-71
[ 1180.933344] mt7601u 1-1.1.3:1.0: Vendor request req:02 off:0080 failed:-71
[ 1181.137208] mt7601u 1-1.1.3:1.0: Vendor request req:02 off:0080 failed:-71
[ 1181.137267] mt7601u: probe of 1-1.1.3:1.0 failed with error -110
[ 1181.141906] usb 1-1.1.3: USB disconnect, device number 10
root@abc-T6Series:/home/abc# uname -r
5.15.0-78-generic
root@abc-T6Series:/home/abc#

**Comment by ccchang12** [comment]
@didadidadi5 這個 topic 是 mt7601u 跑在 x86 Ubuntu 22.04 的 issue, 兩者都與我司 OpenWrt 平台無關, 不適合在這邊討論. 建議你到 MTK 或 Ubuntu 的社群進行討論.

**Comment by didadidadi5** [comment]
> @didadidadi5 這個 topic 是 mt7601u 跑在 x86 Ubuntu 22.04 的 issue, 兩者都與我司 OpenWrt 平台無關, 不適合在這邊討論. 建議你到 MTK 或 Ubuntu 的社群進行討論.

> 其实在nuc977平台也是这种情况，应该是mt7601u驱动可能有什么特别的地方，EEPROM版本不一样？有时候会莫名其妙加载驱动OK！
